### ISSUE TITLE
Marks are positioned badly above U+25CC DOTTED CIRCLE

### ISSUE THREAD

**Issue by dscorbett** [notofonts/syloti-nagri#7]
### Font
NotoSansSylotiNagri-Regular.otf

### Where the font came from, and when
Site: https://github.com/notofonts/syloti-nagri/releases/tag/NotoSansSylotiNagri-v2.002
Date: 2022-09-14

### Font version
Version 2.002

### Issue
Marks above U+25CC DOTTED CIRCLE are placed inconsistently. Some are placed close above the glyph; some are placed higher, at the same vertical position as they are placed above letters. Also, U+A80B SYLOTI NAGRI SIGN ANUSVARA and U+A80B SYLOTI NAGRI SIGN ANUSVARA overlap each other above U+25CC.

### Character data
◌ꠂ◌꠆◌ꠋ◌ꠦ◌ꠦꠋ
U+25CC DOTTED CIRCLE
U+A802 SYLOTI NAGRI SIGN DVISVARA
U+25CC DOTTED CIRCLE
U+A806 SYLOTI NAGRI SIGN HASANTA
U+25CC DOTTED CIRCLE
U+A80B SYLOTI NAGRI SIGN ANUSVARA
U+25CC DOTTED CIRCLE
U+A826 SYLOTI NAGRI VOWEL SIGN E
U+25CC DOTTED CIRCLE
U+A826 SYLOTI NAGRI VOWEL SIGN E
U+A80B SYLOTI NAGRI SIGN ANUSVARA

### Screenshot
![◌ꠂ◌꠆◌ꠋ◌ꠦ◌ꠦꠋ](https://user-images.githubusercontent.com/1124347/190180801-e7606a4b-2b4e-4edd-95c5-9c52dfce2612.png)

**Comment by simoncozens** [comment]
I've done what I can with this. The last issue is a toolchain one (https://github.com/googlefonts/ufo2ft/issues/754) so I've added a manual rule to work around it.
