### ISSUE TITLE
U+A826 SYLOTI NAGRI VOWEL SIGN E overlaps other glyphs

### ISSUE THREAD

**Issue by dscorbett** [notofonts/syloti-nagri#8]
### Font
NotoSansSylotiNagri-Regular.otf

### Where the font came from, and when
Site: https://github.com/notofonts/syloti-nagri/releases/tag/NotoSansSylotiNagri-v2.002
Date: 2022-09-14

### Font version
Version 2.002

### Issue
 U+A826 SYLOTI NAGRI VOWEL SIGN E overlaps other glyphs.

### Character data
ꠇꠦꠋꠑꠦ
U+A807 SYLOTI NAGRI LETTER KO
U+A826 SYLOTI NAGRI VOWEL SIGN E
U+A80B SYLOTI NAGRI SIGN ANUSVARA
U+A811 SYLOTI NAGRI LETTER TTHO
U+A826 SYLOTI NAGRI VOWEL SIGN E
ꠇꠦꠋꠄ
U+A807 SYLOTI NAGRI LETTER KO
U+A826 SYLOTI NAGRI VOWEL SIGN E
U+A80B SYLOTI NAGRI SIGN ANUSVARA
U+A804 SYLOTI NAGRI LETTER E
ꠇꠧꠋꠑ
U+A807 SYLOTI NAGRI LETTER KO
U+A827 SYLOTI NAGRI VOWEL SIGN OO
U+A80B SYLOTI NAGRI SIGN ANUSVARA
U+A811 SYLOTI NAGRI LETTER TTHO
ꠇꠤꠋꠑ
U+A807 SYLOTI NAGRI LETTER KO
U+A824 SYLOTI NAGRI VOWEL SIGN I
U+A80B SYLOTI NAGRI SIGN ANUSVARA
U+A811 SYLOTI NAGRI LETTER TTHO

### Screenshot
![ꠇꠦꠋꠑꠦ ꠇꠦꠋꠄ ꠇꠧꠋꠑ ꠇꠤꠋꠑ](https://user-images.githubusercontent.com/1124347/190185328-1b841718-b8e7-4482-8eaa-43ef90d0591b.png)

**Comment by simoncozens** [comment]
I think there was some missing anchoring here, but it looks like it's working now:

![shape](https://github.com/notofonts/syloti-nagri/assets/106728/596f196f-ac92-42c2-8140-c215b50e443e)

The first two examples are still touching but I'm not worried about them as it's clearly legible.
